from . import *

AWS_SERVER_PUBLIC_KEY = config.get('AWS', 'AWS_SERVER_PUBLIC_KEY')
AWS_SERVER_SECRET_KEY = config.get('AWS', 'AWS_SERVER_SECRET_KEY')
AWS_REGION_NAME = config.get('AWS', 'AWS_REGION_NAME')
AWS_SESSION_TOKEN = config.get('AWS', 'AWS_SESSION_TOKEN')
