from . import *

AWS_SERVER_SECRET_KEY = config.get('AWS', 'AWS_SERVER_SECRET_KEY')
AWS_ACCESS_KEY_ID = config.get('AWS', 'AWS_ACCESS_KEY_ID')
AWS_STORAGE_BUCKET_NAME = config.get('AWS', 'AWS_STORAGE_BUCKET_NAME')
AWS_REGION_NAME = config.get('AWS', 'AWS_REGION_NAME')
AWS_DEFAULT_FILE_STORAGE = config.get('AWS', 'AWS_DEFAULT_FILE_STORAGE')
